### PR TITLE
Configure root workspace and new inquire-derive crate

### PR DESCRIPTION
**Pull request by mikaelmello**
This is in preparation for an incoming inquire-derive crate

### CODE REVIEW

**Comment by IniterWorker** [comment]
Perfect @mikaelmello, please re-send me an invite I missed it. I will open a branch to follow your path.

**Comment by mikaelmello** [comment]
Invited again

**Comment by IniterWorker** [comment]
First,  sorry for the delay,
- I rebased your branch history on `main`.
- I am opening a new branch to implement the derive.

If your work is finished, we can move on and merge it.

Thank you so much @mikaelmello!

**Comment by mikaelmello** [comment]
I recreated this PR from scratch because of the many changes since then, see #122

**Pull request closed without merging**
