### PR TITLE
feat: Added initial_str_value for CustomType

### PR DESCRIPTION
**Pull request by FroVolod**
My project needs a with_initial_value() method for CustomType.
This introduces a breaking change by adding a new field to public struct, but it seems to be unavoidable.

### CODE REVIEW

**Comment by frol** [comment]
@mikaelmello Does this solution make sense to you? This would greatly simplify our codebase as we will be able to migrate to CustomType instead of using Text and managing CustomType-like logic manually.

**Comment by mikaelmello** [comment]
Hey @frol , it makes a lot of sense! 

I was just thinking if we should change it to `starting_input` and `with_starting_input`. It's not the best name but it would be consistent with other prompts that also offer this feature, wdyt?

**Comment by frol** [comment]
@mikaelmello The naming suggestion makes a ton of sense, I agree

**Comment by FroVolod** [comment]
@mikaelmello 
> I was just thinking if we should change it to `starting_input` and `with_starting_input`. It's not the best name but it would be consistent with other prompts that also offer this feature, wdyt? @FroVolod

Changed

**Review by mikaelmello — APPROVED** [review]

**Comment by mikaelmello** [comment]
Awesome, thanks for the contribution!

As for the release, unfortunately this year I've let a lot of things accumulate, so before releasing I'm extending the test suite over a little bit to avoid any larger problems. I want to get it done by Jan

**Pull request merged**
